# Generated by Django 3.1.7 on 2021-03-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.TextField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')])),
                ('regions', models.JSONField()),
                ('working_hours', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('region', models.IntegerField()),
                ('delivery_hours', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candy_delivery_app.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DateTimeField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.order')),
            ],
        ),
    ]
